### PR TITLE
Alternative to #84

### PR DESCRIPTION
**Pull request by pchampin**
This takes most of @philarcher's text in #84, but moves it to the note cited by @iherman .

I find this more consistent, but I won't fight for it if people prefer #84 :)

### CODE REVIEW

**Review by dlongley — APPROVED** [review]

**Review by philarcher — APPROVED** [review]
I'm happy with this, sure. I'll ask Dan to look at it too (can't tag him here annoyingly)

**Review by msporny — APPROVED** [review]

**Comment by msporny** [comment]
> I'm happy with this, sure. I'll ask Dan to look at it too (can't tag him here annoyingly)

I think this might do it -- /cc @danbri -- need a review from you on this.

**Comment by danbri** [comment]
Somewhat agnostic. I'm not sure why TriG is "notably"; or CBOR-LD gets mentioned before W3C's own Turtle, RDF/XML formats. Or engagement with the (is it RDF? is it Linked Data? is it in scope?) Microdata.

This is heading in a useful direction, but it still feels worth spelling out in excruciating detail why exactly a system can't be built which meets the needs of the underlying problem, but which keeps the source documents (or information about their hashes) somewhere bigger than a barcode. 

The less you say now, the more you're playing "I feel lucky" with whoever decides that this is the WG for them...

**Comment by pchampin** [comment]
@danbri Turtle and RDF/XML are serializing graphs, not datasets. That's why they do not appear in the list.

As for the "constrained data transfer" use-case, honestly, I don't understand what you feel is missing...

**Review by gkellogg — APPROVED** [review]

**Comment by danbri** [comment]
Don't let me stand in your way with merging this. Maybe mention https://www.w3.org/TR/n-quads/ if you're only caring about datasets in this section? (I missed the section heading - reviewing PRs makes that easy)

**Review by iherman — APPROVED** [review]

**Comment by iherman** [comment]
@pchampin I did not know whether you want to make any more changes; I let you merge it when you feel like it...

**Pull request merged**
